ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.sassnippet.manager.ApplicationKt.module ]
    }
}

security {
    apiKey = "dev-secret-key"
    apiKey = ${?API_KEY}
}

database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/sassnippets"
    jdbcUrl = ${?DB_URL}
    username = "snippet_user"
    username = ${?DB_USER}
    password = "snippet_pass"
    password = ${?DB_PASSWORD}
    maxPoolSize = 10
    maxPoolSize = ${?DB_POOL_SIZE}
}